[project]
name = "VBA-Gems"
description = """
A collection of useful packages
 - CSharpish string formatter
 - That's it
"""
ptrsafe = true 

[references]
"Scripting.Dictionary" = '%WINDIR%\System32\scrrun.dll' 
"Regex 5.5" = '%WINDIR%\System32\vbscript.dll\3'
